### ISSUE TITLE
Get rid of bluebird dependency

### ISSUE THREAD

**Issue by miracle2k** [Jpunt/react-promise-container#6]
Bluebird is pretty big, and as far as I can tell, is only used because of _Promise.props_.

Would you accept a pull request that replaces it with a function we add to this repo (say from https://github.com/expo/promise-props/blob/master/index.js)?

**Comment by Jpunt** [comment]
Yes! That's defiantly on the list 👍

**Comment by Jpunt** [comment]
Better late than never 😅 #59
